### ISSUE TITLE
Version 11.11

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#237]
Can someone make a commit?

https://otland.net/threads/protocol-version-1111.250132/#post-2429301

**Comment by jlcvp** [comment]
**_TO-DO Tasklist_**
- [ ] modify the **protocolgame/protocolgamebase**
   - [ ] change the connection adler to a sequenceNumber
   - [ ] handle compressed packets
- [ ] modify **protocolStatus**
- [ ] modify **protocolSpectator**

**_And maybe ??? (RFC)_**
- [ ] maintain compatibility with 11.10-  


RFC: @Eternal-Scripts @GoularPink @malucooo 
Should we maintain the compatibility with 11.10- protocols?

**Comment by malucooo** [comment]
i gonna work to make an upgrade in protocol this weekend

**Comment by jlcvp** [comment]
@malucooo but should we maintain the compatibility with 11.10- or earlier protocols ?

**Comment by westwol** [comment]
IMO **10** protocol for the mean time it should be kept until protocol. **11.+** is fully supported.

**Comment by Eternal-Scripts** [comment]
ProtocolLogin 100%
Now i am trying to make protocolgame work, in this part enter the Checksum.

In my tests i see the checksum don't change in login (wtf) but anyway i will keep testing here.

**Comment by jlcvp** [comment]
for login you don't need the sequence number, only when the game starts.

One workaround I've found is to put the sequencenumber in the outputmessage.h/cpp in the place of the adler checksum, this makes the protocol11.10- stop working but clients with 11.11+ log in normally. I didn't make any further testes though.

It's important to note that latest 10 clients maybe use this type of protocol.

**Comment by Eternal-Scripts** [comment]
Hmm understood.
So... do you will commit these changes? i think is good for all work in items/monsters/systems of new version, isn't hard to update that things.

**Comment by jlcvp** [comment]
commit beda91b51f9bb2dfeef576f598f6dd73e2a33fd7 from @comedinha closes this.
